//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG.DemoPCBE99925.ManageCourse.WPF.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EG.DemoPCBE99925.ManageCourse.WPF.Views.Resources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Please describe what might caused this error.] 
        ///
        ///{0}.
        /// </summary>
        public static string FeedbackFormBody {
            get {
                return ResourceManager.GetString("FeedbackFormBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Report for {0} {1}.
        /// </summary>
        public static string FeedbackFormSubject {
            get {
                return ResourceManager.GetString("FeedbackFormSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been Impersonate to user {0}..
        /// </summary>
        public static string Impersonate {
            get {
                return ResourceManager.GetString("Impersonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment: {0}.
        /// </summary>
        public static string MainFormEnvironment {
            get {
                return ResourceManager.GetString("MainFormEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User: {0}.
        /// </summary>
        public static string MainFormUser {
            get {
                return ResourceManager.GetString("MainFormUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string MainFormVersion {
            get {
                return ResourceManager.GetString("MainFormVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network is available again.You can safely work..
        /// </summary>
        public static string NetworkAvailable {
            get {
                return ResourceManager.GetString("NetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurs during the establishment of your connection.Check your network connectivity..
        /// </summary>
        public static string NetworkUnavailableOnStart {
            get {
                return ResourceManager.GetString("NetworkUnavailableOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have loose your network connection. All work you are doing now will be loose.Please, reconnect your computer before you perform any other actions..
        /// </summary>
        public static string NoNetworkAvailable {
            get {
                return ResourceManager.GetString("NoNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer is not connected to the network. The application needs a network to run. Check your connection and restart the application after..
        /// </summary>
        public static string NoNetworkAvailableOnStart {
            get {
                return ResourceManager.GetString("NoNetworkAvailableOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have currently no access right to run the application..
        /// </summary>
        public static string ProgramAccessDenied {
            get {
                return ResourceManager.GetString("ProgramAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} is currently not available..
        /// </summary>
        public static string ProgramApplicationUnavailable {
            get {
                return ResourceManager.GetString("ProgramApplicationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string ProgramStartup {
            get {
                return ResourceManager.GetString("ProgramStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Security....
        /// </summary>
        public static string SplashFormCheckingSecurity {
            get {
                return ResourceManager.GetString("SplashFormCheckingSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Remoting....
        /// </summary>
        public static string SplashFormConfiguringRemoting {
            get {
                return ResourceManager.GetString("SplashFormConfiguringRemoting", resourceCulture);
            }
        }
    }
}
