trigger:
  branches:
    include:     
    - main
    - master
    - release/*
    - develop/*
  paths:
    include:
      - BE/$(servicename)/*
      - Shared/*

resources:
  repositories:
  - repository: templates
    type: git
    endpoint: EliaGroupCollectionRepo
    name: DevOps/Templating

variables:
  majorVersion: 1
  minorVersion: 0

name: $(majorVersion).$(minorVersion).$(Year:yy)$(DayOfYear)$(Rev:.r)

stages:
- template: Build/BuildAndPublish.yml@templates
  parameters:
    serviceName: '$(servicename)'
    projectName: 'DemoPCBE99925'
    projectFileName: 'Host'
    folderPrefix: '' 
    sharedFolderName: 'Shared/'
    beFolder: 'BE'
    owaspDependencyCheckEnabled: true
    sonarQubeEnabled: true
    collectCodeCoverage: true
    publishTestResult: true
    publishCodeCoverageResult: true
